### ISSUE TITLE
Need Navigation package to run it?

### ISSUE THREAD

**Issue by FaboNo** [tu-darmstadt-ros-pkg/hector_navigation#13]
I am wondering whether we need the ROS navigation package to run Hector navigation? Indeed  costmap_2d.h and costmap_2d_ros.h are included in hector_exploration_planner.h and costmap is part of the Ros navigation package. 
This why I guess you define plugins?

**Comment by lukelu0520** [comment]
Hi @FaboNo , we were wondering if you find a solution. Is Navigation required for Hector navigation ?
