### ISSUE TITLE
tf error

### ISSUE THREAD

**Issue by misaq-s** [tu-darmstadt-ros-pkg/hector_navigation#16]
my ros is melodic 
i have this errors in my catkin_make

r_exploration_planner.cpp:1148:21: error: ‘tf’ has not been declared
         tf::Stamped<tf::Pose> robotPose;

r_exploration_planner.cpp:1148:31: error: ‘robotPose’ was not declared in this scope
         tf::Stamped<tf::Pose> robotPose;

**Comment by StefanFabian** [comment]
Congrats on your first issue!
For future issues please include more information such as the branch you're using and the OS you're on.
Also, it is way more readable if you put error messages and code in code boxes
```
like
this
```
To do so you have to write
\`\`\`
Multiline code
or
Error message
\`\`\`

Regarding your issue, are you on the melodic-devel branch?
If not, try switching to that branch and let me know if this fixed it.

**Comment by misaq-s** [comment]
Hi,
I'm sorry about my bad formatted-text.
Thank's to you, fixed by melodic-devel branch. :+1:
