### ISSUE TITLE
compiling error in kinetic

### ISSUE THREAD

**Issue by fakca** [tu-darmstadt-ros-pkg/hector_navigation#17]
Hi,
when i compile with `catkin build` and `catkin make` i am getting this following error:

`~/catkin_ws/src/hector_navigation/hector_exploration_planner/src/hector_exploration_planner.cpp:286:5: error: ‘tf’ has not been declared
     tf::Stamped<tf::Pose> robotPose;`

i already add tf package referance to `pagkages.xml` and `CMakeLists.txt`. But nothing to changed.

how can solve it? Thx.

Note:
OS: ubuntu 16.04
ros distro: kinetic

**Comment by StefanFabian** [comment]
Can you check if the `melodic-devel` branch works?
See #16.

**Comment by fakca** [comment]
i tried for melodic-devel, master and catkin branchs. but the same problem persists.

**Comment by StefanFabian** [comment]
Since there's currently no maintainer for this repo and especially not on kinetic, you'll, unfortunately, have to find a fix yourself.
It sounds like a missing include, though, so you might want to check where `tf::Stamped` is declared.

**Comment by fakca** [comment]
okay Thank you. i will search about `tf` on this issue. By the way is there any node for `full area coverage` in this repo (eg hector_exploration_planning)?

**Comment by PhehJingJie** [comment]
Hi @muratKeys , sorry to bother but did you managed to implement hector_navigation on ROS Kinetic?
