### ISSUE TITLE
Error with catkin_make 

### ISSUE THREAD

**Issue by Sprinzzzz** [tu-darmstadt-ros-pkg/hector_navigation#22]
Hello,

I am trying to set navigation for the map generated from hector slam. I performed the following action,
1. cloned the melodic branch to the src directory of ROS
2. Tried catkin_make

On performing catkin_make, the obtained error is

`` catkin_make
Base path: /home/nvidia/trial_ws
Source space: /home/nvidia/trial_ws/src
Build space: /home/nvidia/trial_ws/build
Devel space: /home/nvidia/trial_ws/devel
Install space: /home/nvidia/trial_ws/install
####
####
####
####
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_nodejs
[  0%] Built target _hector_elevation_msgs_generate_messages_check_deps_ElevationMapMetaData
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target _hector_elevation_msgs_generate_messages_check_deps_ElevationGrid
[  0%] Built target nav_msgs_generate_messages_py
[  0%] Built target _hector_nav_msgs_generate_messages_check_deps_GetRecoveryInfo
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target _hector_nav_msgs_generate_messages_check_deps_GetNormal
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target _hector_nav_msgs_generate_messages_check_deps_GetRobotTrajectory
[  0%] Built target _hector_nav_msgs_generate_messages_check_deps_GetDistanceToObstacle
[  1%] Built target hector_driving_aid_markers_node
[  1%] Built target rosgraph_msgs_generate_messages_py
[  1%] Built target _catkin_empty_exported_target
[  1%] Built target _hector_nav_msgs_generate_messages_check_deps_GetSearchPosition
[  1%] Built target actionlib_msgs_generate_messages_eus
[  1%] Built target actionlib_msgs_generate_messages_nodejs
[  1%] Built target actionlib_msgs_generate_messages_lisp
[  1%] Built target actionlib_msgs_generate_messages_py
[  1%] Built target roscpp_generate_messages_nodejs
[  1%] Built target actionlib_msgs_generate_messages_cpp
[  1%] Built target roscpp_generate_messages_eus
[  1%] Built target roscpp_generate_messages_lisp
[  1%] Built target roscpp_generate_messages_cpp
[  1%] Built target rosgraph_msgs_generate_messages_cpp
[  1%] Built target rosgraph_msgs_generate_messages_eus
[  1%] Built target rosgraph_msgs_generate_messages_lisp
[  1%] Built target rosgraph_msgs_generate_messages_nodejs
[  1%] Built target roscpp_generate_messages_py
[  1%] Built target tf2_msgs_generate_messages_lisp
[  1%] Built target tf2_msgs_generate_messages_cpp
[  2%] Built target tf2_msgs_generate_messages_eus
[  2%] Built target occ_grid_mapping
[  2%] Built target tf2_msgs_generate_messages_py
[  2%] Built target tf2_msgs_generate_messages_nodejs
[  3%] Built target gtest
[  3%] Built target bond_generate_messages_lisp
[  4%] Built target map_to_image_node
[  4%] Built target actionlib_generate_messages_eus
[  4%] Built target sensor_msgs_generate_messages_py
[  4%] Built target sensor_msgs_generate_messages_nodejs
[  5%] Built target slam_gmapping_nodelet
[  5%] Built target tf_generate_messages_lisp
[  5%] Built target tf_generate_messages_eus
[  5%] Built target sensor_msgs_generate_messages_cpp
[  5%] Built target sensor_msgs_generate_messages_lisp
[  5%] Built target sensor_msgs_generate_messages_eus
[  5%] Built target tf_generate_messages_nodejs
[  5%] Built target tf_generate_messages_py
[  5%] Built target tf_generate_messages_cpp
[  5%] Built target actionlib_generate_messages_cpp
[  5%] Built target actionlib_generate_messages_lisp
[  5%] Built target actionlib_generate_messages_py
[  5%] Built target actionlib_generate_messages_nodejs
[  5%] Built target bond_generate_messages_nodejs
[  5%] Built target bond_generate_messages_eus
[  5%] Built target nodelet_generate_messages_py
[  5%] Built target nodelet_generate_messages_eus
[  5%] Built target nodelet_generate_messages_nodejs
[  5%] Built target bond_generate_messages_py
[  5%] Built target nodelet_generate_messages_cpp
[  7%] Built target hector_elevation_visualization_gencfg
[  7%] Built target bond_generate_messages_cpp
[  7%] Built target visualization_msgs_generate_messages_eus
[  7%] Built target nodelet_generate_messages_lisp
[  7%] Built target imu_attitude_to_tf_node
[  8%] Built target pose_and_orientation_to_imu_node
[  8%] Built target visualization_msgs_generate_messages_nodejs
[  8%] Built target visualization_msgs_generate_messages_lisp
[  8%] Built target visualization_msgs_generate_messages_cpp
[  8%] Built target visualization_msgs_generate_messages_py
[  8%] Built target hector_path_follower
[  9%] Built target hector_path_follower_node
[ 11%] Built target amcl_map
[ 11%] Built target hector_costmap_gencfg
[ 14%] Built target amcl_pf
[ 14%] Built target dynamic_reconfigure_generate_messages_eus
[ 14%] Built target dynamic_reconfigure_generate_messages_lisp
[ 15%] Built target amcl_gencfg
[ 15%] Built target dynamic_reconfigure_generate_messages_py
[ 15%] Built target dynamic_reconfigure_generate_messages_cpp
[ 15%] Built target dynamic_reconfigure_gencfg
[ 15%] Built target dynamic_reconfigure_generate_messages_nodejs
[ 15%] Built target topic_tools_generate_messages_py
[ 15%] Built target topic_tools_generate_messages_nodejs
[ 15%] Built target std_srvs_generate_messages_lisp
[ 15%] Built target std_srvs_generate_messages_eus
[ 15%] Built target topic_tools_generate_messages_cpp
[ 15%] Built target std_srvs_generate_messages_cpp
[ 15%] Built target std_srvs_generate_messages_nodejs
[ 15%] Built target std_srvs_generate_messages_py
[ 15%] Built target topic_tools_generate_messages_eus
[ 15%] Built target diagnostic_msgs_generate_messages_nodejs
[ 15%] Built target topic_tools_generate_messages_lisp
[ 15%] Built target diagnostic_msgs_generate_messages_eus
[ 15%] Built target diagnostic_msgs_generate_messages_cpp
[ 15%] Built target diagnostic_msgs_generate_messages_lisp
[ 15%] Built target diagnostic_msgs_generate_messages_py
[ 16%] Built target fake_localization
[ 17%] Built target voxel_grid
[ 17%] Built target hector_gps_calibration
[ 17%] Built target map_msgs_generate_messages_nodejs
[ 19%] Built target costmap_2d_gencfg
[ 19%] Built target _hector_mapping_generate_messages_check_deps_HectorIterData
[ 19%] Built target map_msgs_generate_messages_lisp
[ 19%] Built target map_msgs_generate_messages_eus
[ 19%] Built target _hector_mapping_generate_messages_check_deps_HectorDebugInfo
[ 19%] Built target map_msgs_generate_messages_cpp
[ 19%] Built target map_msgs_generate_messages_py
[ 19%] Built target hector_exploration_planner_gencfg
[ 20%] Built target dwa_local_planner_gencfg
[ 21%] Built target base_local_planner_gencfg
[ 21%] Built target _costmap_2d_generate_messages_check_deps_VoxelGrid
[ 21%] Built target global_planner_gencfg
[ 21%] Built target move_base_msgs_generate_messages_py
[ 21%] Built target move_base_msgs_generate_messages_eus
[ 21%] Built target _navfn_generate_messages_check_deps_MakeNavPlan
[ 21%] Built target _base_local_planner_generate_messages_check_deps_Position2DInt
[ 21%] Built target move_base_msgs_generate_messages_cpp
[ 22%] Built target move_base_gencfg
[ 22%] Built target move_base_msgs_generate_messages_lisp
[ 22%] Built target _navfn_generate_messages_check_deps_SetCostmap
[ 22%] Built target move_base_msgs_generate_messages_nodejs
[ 22%] Built target diff_drive_xacro_generated_to_devel_space_
[ 22%] Built target hector_elevation_msgs_generate_messages_cpp
[ 23%] Built target hector_elevation_msgs_generate_messages_lisp
[ 23%] Built target hector_elevation_msgs_generate_messages_nodejs
[ 26%] Built target hector_elevation_msgs_generate_messages_py
[ 26%] Built target hector_elevation_msgs_generate_messages_eus
[ 28%] Built target hector_nav_msgs_generate_messages_nodejs
[ 30%] Built target hector_nav_msgs_generate_messages_py
[ 33%] Built target hector_nav_msgs_generate_messages_lisp
[ 34%] Built target hector_nav_msgs_generate_messages_cpp
[ 36%] Built target hector_nav_msgs_generate_messages_eus
[ 36%] Built target map_server_image_loader
[ 39%] Built target odometry
[ 39%] Built target map_server-map_saver
[ 40%] Built target mapping
[ 41%] Built target rtest
[ 42%] Built target slam_gmapping
[ 44%] Built target slam_gmapping_replay
[ 45%] Built target hector_trajectory_server
[ 46%] Built target simple_exploration_controller
[ 47%] Built target hector_elevation_visualization_node
[ 48%] Built target ElevationMappingNode
[ 50%] Built target hector_map_server
[ 51%] Built target amcl_sensors
[ 52%] Built target hector_mapping_generate_messages_eus
[ 53%] Built target hector_mapping_generate_messages_py
[ 54%] Built target hector_mapping_generate_messages_cpp
[ 55%] Built target hector_costmap
[ 55%] Built target hector_mapping_generate_messages_lisp
[ 55%] Built target ElevationMapping
[ 57%] Built target hector_mapping_generate_messages_nodejs
[ 57%] Built target costmap_2d_generate_messages_nodejs
[ 58%] Built target costmap_2d_generate_messages_py
[ 59%] Built target costmap_2d_generate_messages_lisp
[ 59%] Linking CXX executable /home/nvidia/trial_ws/devel/lib/hector_gps_calibration/hector_gps_calibration_node
[ 60%] Built target costmap_2d_generate_messages_cpp
[ 60%] Built target costmap_2d_generate_messages_eus
[ 60%] Built target base_local_planner_generate_messages_eus
[ 60%] Built target base_local_planner_generate_messages_cpp
[ 61%] Built target base_local_planner_generate_messages_py
[ 63%] Built target base_local_planner_generate_messages_lisp
[ 63%] Built target base_local_planner_generate_messages_nodejs
[ 64%] Built target navfn_generate_messages_eus
[ 65%] Built target navfn_generate_messages_cpp
[ 66%] Built target hector_exploration_planner
[ 67%] Built target navfn_generate_messages_nodejs
[ 67%] Built target navfn_generate_messages_lisp
[ 69%] Built target navfn_generate_messages_py
[ 69%] Built target hector_elevation_msgs_generate_messages
[ 69%] Built target hector_nav_msgs_generate_messages
[ 69%] Built target map_server
[ 70%] Built target geotiff_writer
[ 70%] Built target amcl
[ 70%] Built target hector_mapping_generate_messages
Scanning dependencies of target hector_exploration_base_global_planner_plugin
[ 70%] Built target costmap_2d_generate_messages
[ 71%] Built target hector_mapping
[ 71%] Built target base_local_planner_generate_messages
[ 75%] Built target costmap_2d
[ 75%] Built target navfn_generate_messages
[ 75%] Building CXX object hector_navigation/hector_exploration_planner/CMakeFiles/hector_exploration_base_global_planner_plugin.dir/src/hector_exploration_base_global_planner_plugin.cpp.o
[ 76%] Built target geotiff_saver
[ 76%] Built target geotiff_node
[ 77%] Built target hector_geotiff_plugins
[ 78%] Built target costmap_2d_node
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::base::CheckOpMessageBuilder::ForVar2()'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_ltsolve'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `fLI::FLAGS_v'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_start'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_schol'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::InitVLOG3__(int**, int*, char const*, int)'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_finish'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_post'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_etree'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_calloc'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_free_factor'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_zeros'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_multiply'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `dpotrs_'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_pinv'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_counts'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_print_common'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_pvec'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int, google::CheckOpString const&)'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_solve'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_compress'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessage::LogMessage(char const*, int)'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_malloc'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_sfree'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_free_sparse'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_free'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_free_dense'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_spfree'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_ipvec'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_amd'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_transpose'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `dgels_'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `dsyrk_'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_factorize'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_camd'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_analyze_p'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessage::~LogMessage()'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::kLogSiteUninitialized'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_chol'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_triplet_to_sparse'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessage::stream()'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `dpotrf_'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_nfree'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_amd'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_cumsum'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_symperm'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_cholsol'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cholmod_analyze'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `cs_di_lsolve'
/home/nvidia/trial_ws/devel/lib/libhector_gps_calibration.so: undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'
collect2: error: ld returned 1 exit status
[ 79%] Built target costmap_2d_cloud
hector_navigation/hector_gps_calibration/CMakeFiles/hector_gps_calibration_node.dir/build.make:130: recipe for target '/home/nvidia/trial_ws/devel/lib/hector_gps_calibration/hector_gps_calibration_node' failed
make[2]: *** [/home/nvidia/trial_ws/devel/lib/hector_gps_calibration/hector_gps_calibration_node] Error 1
CMakeFiles/Makefile2:10167: recipe for target 'hector_navigation/hector_gps_calibration/CMakeFiles/hector_gps_calibration_node.dir/all' failed
make[1]: *** [hector_navigation/hector_gps_calibration/CMakeFiles/hector_gps_calibration_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 79%] Built target costmap_2d_markers
[ 82%] Built target layers
[ 82%] Linking CXX shared library /home/nvidia/trial_ws/devel/lib/libhector_exploration_base_global_planner_plugin.so
[ 82%] Built target hector_exploration_base_global_planner_plugin
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

``
Is there a way to eliminate this error?
Thanks in advance.

**Comment by kdaun** [comment]
Can give us some more background about your system? As the user name is _nvidia_ I am guessing it is an ARM based nvidia board?

Hector_gps_calibration is not able to resolve the ceres dependency properly. Is [ceres_catkin](https://github.com/ethz-asl/ceres_catkin) present in your workspace? if yes, which version of ceres_catkin are you using?

**Comment by Sprinzzzz** [comment]
I am using nvidia jetson board to create an autonomous mobile robot.  The OS is ubuntu 18.01

Unfortunately, I dont have ceres catkin package in my workspace. I tried to install ceres catkin from http://packages.ros.org/ros/ubuntu/pool/main/c/ceres-solver/
I tried with the following versions:
1. ceres-solver-doc_1.12.0+dfsg0-1_all.deb
2. ceres-solver-doc_1.12.0+dfsg0-1~ubuntu16.10.1_all.deb

Still I face the same issue in building the workspace using catkin_make.
Could you please provide some help on how to set it up?

**Comment by Sprinzzzz** [comment]
Thank you very much. Issue solved by using ceres_catkin and the dependencies from the following repositories :

https://github.com/ethz-asl/suitesparse
https://github.com/ethz-asl/glog_catkin
https://github.com/ethz-asl/gflags_catkin
https://github.com/ethz-asl/catkin_simple

**Comment by robbiedood** [comment]
Dear @Sprinzzzz , we got the same issue, but have no idea where we should put ceres_catkin and its dependencies in order to catkin_make successfully. Did you put them under /src or directly under root workspace ?

Also, https://github.com/ethz-asl/catkin_simple is not available anymore, we found an alternative: https://github.com/catkin/catkin_simple

Thank you,
-- Luke

**Comment by robbiedood** [comment]
> Dear @Sprinzzzz , we got the same issue, but have no idea where we should put ceres_catkin and its dependencies in order to catkin_make successfully. Did you put them under /src or directly under root workspace ?
> 
> Also, https://github.com/ethz-asl/catkin_simple is not available anymore, we found an alternative: https://github.com/catkin/catkin_simple
> 
> Thank you,
> -- Luke

Problem solved. Do not compile all of them at once, need to put under /src and compile dependencies in following sequence:

> suitesparse, gflags_catkin, catkin_simple (these three could be compiled in the same time)

and then

> glog_catkin

and then

> ceres_catkin

and finally 

> hector_navigation

-- Luke
