### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by sinadunk23** [tu-darmstadt-ros-pkg/hector_navigation#23]
Hello, i am trying to use the hector navigation package for exploration of unknown map for the hector_quadrotor package. while trying to run the hector_exploration_node i get the following error:

**[ERROR] [1582991686.126575728, 1172.588000000]: Do not call canTransform or lookupTransform with a timeout unless you are using another thread for populating data. Without a dedicated thread it will always timeout.  If you have a seperate thread servicing tf messages, call setUsingDedicatedThread(true) on your Buffer instance.**

can you help me fix it?
and can you please assist me in properly running the nodes or launch files needed for autonomous exploration in the right order.

**Comment by Savanth123** [comment]
Hi @sinadunk23 ,I am also facing same issue while running the hector_exploration_node.Have you resolved the problem or else it still persists
Thanking you 
-savanth

**Comment by sinadunk23** [comment]
Hello, No we eventually used a combination of other packages to perform
exploration. My thesis will be completed in a few months, and I will upload
all of the codes and files on my Github.
Best regards.
Sina

**Comment by PhehJingJie** [comment]
Hi did anyone solved this problem?

**Comment by Silviis** [comment]
Hi! I'm facing the same problem. Setting the `buffer_.setUsingDedicatedThread(true);` helps but then I get following warning message and situation is pretty much same.

**Warning: Invalid argument "/map" passed to canTransform argument target_frame in tf2 frame_ids cannot start with a '/' like: 
         at line 134 in /tmp/binarydeb/ros-melodic-tf2-0.6.5/src/buffer_core.cpp**

Might it be problem with tf2 compatibility?

**Comment by robbiedood** [comment]
We got the same issue as well. Hope to hear more ideas from you to solve the issue.

**Comment by robbiedood** [comment]
> We got the same issue as well. Hope to hear more ideas from you to solve the issue.

Problem solved, below is our team's solution:
Inside hector_exploration_node folder:

1) avoid parallel threading error by
> add buffer_.setUsingDedicatedThread(true) right before it goes into costmap instance in src/exploration_node.cpp. 

2) avoid tf2_ros compatibility issue by
> remove '/' from /map and /base_link in config/costmap.yaml. 

Hope to know if it works to you. @Silviis

**Comment by StefanFabian** [comment]
Good to hear that you solved the issue @lukelu0520.
Perhaps you could make a PR with the necessary changes.

**Comment by robbiedood** [comment]
@StefanFabian , glad to hear from you. PR #27 has been submitted for your review.

**Comment by Silviis** [comment]
> > We got the same issue as well. Hope to hear more ideas from you to solve the issue.
> 
> Problem solved, below is our team's solution:
> Inside hector_exploration_node folder:
> 
>     1. avoid parallel threading error by
> 
> 
> > add buffer_.setUsingDedicatedThread(true) right before it goes into costmap instance in src/exploration_node.cpp.
> 
>     1. avoid tf2_ros compatibility issue by
> 
> 
> > remove '/' from /map and /base_link in config/costmap.yaml.
> 
> Hope to know if it works to you. @Silviis

@lukelu0520 Yep, the issue is gone after the merge! Thanks!
