### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by tomikawa-0316** [tu-darmstadt-ros-pkg/hector_navigation#32]
What kind of node do I need to start to work with the video below?

https://www.youtube.com/watch?v=PKI378kadp8

I want to know the documentation to work

**Comment by StefanFabian** [comment]
I am sorry but GitHub issues are the wrong place for general questions.
Please ask your question on (ROS Answers)[https://answers.ros.org/questions/] and to get useful answers, be more specific about what you want to achieve.
And here's the (available documentation)[http://wiki.ros.org/hector_navigation] (though it's not much).
